### ISSUE TITLE
Initial public address and secret key hard coded

### ISSUE THREAD

**Issue by semiversus** [okcashpro/okcash.paperwallets#1]
Visiting the site you're welcomed by an initial OKCash address (`PQZRRuwxY3fKebtYsfSs3jW6wFcQXPSRWR`) and secret (`7APgd9WLzLVEfdm3bLxjb1G6ptb4Xcsw3fM27As2bfojr1dLQr1`). They are hard coded in the `index.html` files. Searching the public address on google you'll find people using this address. Looking it up in blockchain explorer this wallet is used quiet heavy: https://chainz.cryptoid.info/ok/address.dws?PQZRRuwxY3fKebtYsfSs3jW6wFcQXPSRWR.htm

Why would you hard code the initial address? Haven't checked if the secret is working. If this is the correct secret everybody is able to get the OKCash transferred to this wallet. If secret is wrong some evil "genius" will have the right secret and is able to get all the OKCash.

Maybe this happened by accident but it's a serious problem! Please don't populate hard coded addresses when people think they are randomly generated. At least after pushing *generate* they're looking randomly generated - my confidence if this is true is at least diminished.

**Comment by oktoshi** [comment]
Issue fixed, thanks.
